spring.application.name=product-service
spring.data.mongodb.uri=mongodb+srv://product-service:tVfU8uAVlHhRvGXf@cluster0.uhlwdu4.mongodb.net/productDB?appName=Cluster0
spring.data.mongodb.database=productDB
spring.data.mongodb.authentication-database=admin
